package com.bar.gestioncocktail.controller;

import com.bar.gestioncocktail.dto.AuditLogResponseDTO;
import com.bar.gestioncocktail.model.User;
import com.bar.gestioncocktail.service.AuditLogService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * REST controller for retrieving and recording system audit logs.
 * Restricted primarily to administrators for traceability and compliance.
 */
@RestController
@RequestMapping("/api/audit-logs")
@Tag(name = "Audit Logs", description = "System action history and operation traceability")
public class AuditLogController {
    private final AuditLogService auditLogService;

    /**
     * Constructs the controller with the audit log service dependency.
     *
     * @param auditLogService Audit log service
     */
    public AuditLogController(AuditLogService auditLogService) {
        this.auditLogService = auditLogService;
    }

    /**
     * Retrieves all system audit logs.
     *
     * @return List of all audit logs ordered by timestamp descending
     */
    @GetMapping
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get all system audit logs (ADMIN)", description = "Retrieves complete audit logs history ordered by timestamp descending.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAllAuditLogs() {
        return ResponseEntity.ok(auditLogService.getAllAuditLogs().stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs generated by a specific user.
     *
     * @param userId User identifier
     * @return List of matching audit logs
     */
    @GetMapping("/user/{userId}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by user (ADMIN)", description = "Filters system audit logs for a specific user.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByUser(
        @Parameter(description = "User identifier") @PathVariable Long userId) {
        User user = new User();
        user.setId(userId);
        return ResponseEntity.ok(auditLogService.getAuditLogsByUser(user).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs filtered by action type.
     *
     * @param action Action name (e.g. 'CREATE', 'UPDATE', 'DELETE')
     * @return List of matching audit logs
     */
    @GetMapping("/action/{action}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by action type (ADMIN)", description = "Filters audit logs by action type.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByAction(
        @Parameter(description = "Action name") @PathVariable String action) {
        return ResponseEntity.ok(auditLogService.getAuditLogsByAction(action).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs for a specific entity type (e.g. 'Commande', 'Cocktail').
     *
     * @param entityType Entity type name
     * @return List of matching audit logs
     */
    @GetMapping("/entity-type/{entityType}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by entity type (ADMIN)", description = "Filters audit logs by target entity type.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByEntityType(
        @Parameter(description = "Entity type name") @PathVariable String entityType) {
        return ResponseEntity.ok(auditLogService.getAuditLogsByEntityType(entityType).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs for a specific entity identifier.
     *
     * @param entityId Entity identifier
     * @return List of matching audit logs
     */
    @GetMapping("/entity-id/{entityId}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by entity ID (ADMIN)", description = "Filters audit logs by specific entity ID.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByEntityId(
        @Parameter(description = "Entity identifier") @PathVariable Long entityId) {
        return ResponseEntity.ok(auditLogService.getAuditLogsByEntityId(entityId).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs within a time range.
     *
     * @param debut Start date and time
     * @param fin   End date and time
     * @return List of audit logs in time range
     */
    @GetMapping("/date")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by date range (ADMIN)", description = "Filters audit logs between start and end timestamps.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByDate(
        @RequestParam LocalDateTime debut,
        @RequestParam LocalDateTime fin) {
        return ResponseEntity.ok(auditLogService.getAuditLogsByDate(debut, fin).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Retrieves audit logs for a specific user within a date range.
     *
     * @param userId User identifier
     * @param debut  Start date and time
     * @param fin    End date and time
     * @return List of filtered audit logs
     */
    @GetMapping("/user/{userId}/date")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs by user and date range (ADMIN)", description = "Filters audit logs for a user within a timestamp range.")
    @ApiResponse(responseCode = "200", description = "Audit logs retrieved successfully")
    public ResponseEntity<List<AuditLogResponseDTO>> getAuditLogsByUserAndDate(
        @PathVariable Long userId,
        @RequestParam LocalDateTime debut,
        @RequestParam LocalDateTime fin) {
        User user = new User();
        user.setId(userId);
        return ResponseEntity.ok(auditLogService.getAuditLogsByUserAndDate(user, debut, fin).stream()
            .map(AuditLogResponseDTO::from).toList());
    }

    /**
     * Manually records an audit log entry.
     *
     * @param userId     Triggering user ID
     * @param action     Action description
     * @param entityType Target entity type
     * @param entityId   Target entity ID
     * @param details    Detailed textual description
     * @param ipAddress  Client IP address
     * @return HTTP 200 OK
     */
    @PostMapping("/log")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Record audit log entry", description = "Explicitly records a log entry in system audit logs.")
    @ApiResponse(responseCode = "200", description = "Audit log recorded successfully")
    public ResponseEntity<Void> logAction(
        @RequestParam Long userId,
        @RequestParam String action,
        @RequestParam String entityType,
        @RequestParam Long entityId,
        @RequestParam String details,
        @RequestParam String ipAddress) {
        User user = new User();
        user.setId(userId);
        auditLogService.logAction(user, action, entityType, entityId, details, ipAddress);
        return ResponseEntity.ok().build();
    }
}
