package com.bar.gestioncocktail.service;

import com.bar.gestioncocktail.model.AuditLog;
import com.bar.gestioncocktail.model.User;
import com.bar.gestioncocktail.repository.AuditLogRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Business service for logging and querying audit log traces.
 */
@Service
@Transactional
public class AuditLogService {
    private final AuditLogRepository auditLogRepository;
    private final TimeService timeService;

    /**
     * Constructs the service with audit log repository and time service dependencies.
     *
     * @param auditLogRepository JPA repository for audit entries
     * @param timeService Time service provider
     */
    public AuditLogService(AuditLogRepository auditLogRepository, TimeService timeService) {
        this.auditLogRepository = auditLogRepository;
        this.timeService = timeService;
    }

    /**
     * Creates and persists a new audit log entry.
     *
     * @param auditLog Audit log entry to persist
     * @return Persisted audit log entry
     */
    public AuditLog createAuditLog(AuditLog auditLog) {
        auditLog.setTimestamp(timeService.now());
        return auditLogRepository.save(auditLog);
    }


    /**
     * Retrieves all audit logs ordered by timestamp descending.
     *
     * @return List of all audit logs
     */
    public List<AuditLog> getAllAuditLogs() {
        return auditLogRepository.findAllByOrderByTimestampDesc();
    }

    /**
     * Retrieves audit logs generated by a specific user.
     *
     * @param user Target user
     * @return List of matching audit entries
     */
    public List<AuditLog> getAuditLogsByUser(User user) {
        return auditLogRepository.findByUser(user);
    }

    /**
     * Searches audit logs by action type.
     *
     * @param action Action name
     * @return List of audit entries
     */
    public List<AuditLog> getAuditLogsByAction(String action) {
        return auditLogRepository.findByAction(action);
    }

    /**
     * Searches audit logs by entity type.
     *
     * @param entityType Entity type
     * @return List of audit entries
     */
    public List<AuditLog> getAuditLogsByEntityType(String entityType) {
        return auditLogRepository.findByEntityType(entityType);
    }

    /**
     * Searches audit logs by entity identifier.
     *
     * @param entityId Entity ID
     * @return List of audit entries
     */
    public List<AuditLog> getAuditLogsByEntityId(Long entityId) {
        return auditLogRepository.findByEntityId(entityId);
    }

    /**
     * Searches audit logs within a time interval.
     *
     * @param debut Start timestamp
     * @param fin End timestamp
     * @return List of audit entries
     */
    public List<AuditLog> getAuditLogsByDate(LocalDateTime debut, LocalDateTime fin) {
        return auditLogRepository.findByTimestampBetween(debut, fin);
    }

    /**
     * Searches audit logs for a user within a time interval.
     *
     * @param user Target user
     * @param debut Start timestamp
     * @param fin End timestamp
     * @return List of audit entries
     */
    public List<AuditLog> getAuditLogsByUserAndDate(User user, LocalDateTime debut, LocalDateTime fin) {
        return auditLogRepository.findByUserAndTimestampBetween(user, debut, fin);
    }

    /**
     * Utility method to log an action audit trace.
     *
     * @param user User initiating the action
     * @param action Action name (e.g. 'CREATE_COMMANDE')
     * @param entityType Entity type (e.g. 'Commande')
     * @param entityId Entity identifier
     * @param details Textual operation details
     * @param ipAddress Client IP address
     */
    public void logAction(User user, String action, String entityType, Long entityId, String details, String ipAddress) {
        AuditLog auditLog = new AuditLog();
        auditLog.setUser(user);
        auditLog.setAction(action);
        auditLog.setEntityType(entityType);
        auditLog.setEntityId(entityId);
        auditLog.setDetails(details);
        auditLog.setIpAddress(ipAddress);
        auditLog.setTimestamp(timeService.now());
        auditLogRepository.save(auditLog);
    }
}