package com.bar.gestioncocktail.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;

/**
 * Data Transfer Object representing a cocktail in profitability rankings.
 *
 * @param cocktailId             Unique cocktail identifier
 * @param nom                    Commercial drink title
 * @param prixTTC                Selling price including VAT in EUR
 * @param prixHT                 Selling price excluding VAT in EUR
 * @param recipeCost             Total recipe unit cost (COGS) in EUR
 * @param grossMargin            Gross margin amount in EUR
 * @param grossMarginPercentage  Gross margin percentage
 * @param quantiteVendue         Total sales volume (units sold)
 * @param totalMarginGenerated   Total gross profit generated by this drink (quantiteVendue * grossMargin)
 */
@Schema(description = "Cocktail profitability ranking entry")
public record ProfitableCocktailDTO(
    @Schema(description = "Cocktail ID", example = "1")
    Long cocktailId,

    @Schema(description = "Drink title", example = "Mojito")
    String nom,

    @Schema(description = "Selling price with VAT in EUR", example = "9.50")
    BigDecimal prixTTC,

    @Schema(description = "Selling price without VAT in EUR", example = "7.92")
    BigDecimal prixHT,

    @Schema(description = "Recipe cost in EUR", example = "1.55")
    BigDecimal recipeCost,

    @Schema(description = "Unit gross margin amount in EUR", example = "6.37")
    BigDecimal grossMargin,

    @Schema(description = "Unit gross margin percentage", example = "80.43")
    BigDecimal grossMarginPercentage,

    @Schema(description = "Total units sold", example = "24")
    long quantiteVendue,

    @Schema(description = "Total cumulative gross margin generated in EUR", example = "152.88")
    BigDecimal totalMarginGenerated
) {}
