# Profile TEST — Base de données de test (Seeding automatique des 99 cocktails)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:gestion_cocktail_test}?sslmode=disable}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${TEST_DB_PASSWORD:${POSTGRES_PASSWORD:${DB_PASSWORD:KZiXrsAw/asRtE8YJuxA8LkWtDXK5rPBmiriAHAu+7Q=}}}}

server:
  port: ${SERVER_PORT:8080}

logging:
  file:
    path: ${LOG_PATH:target/logs}
  level:
    org.springframework.security: INFO
    com.bar.gestioncocktail: INFO
    org.hibernate.SQL: off
