spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_cocktail
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    jwt:
      secret: "QW1wQ2h1bG9rZV9zZWNyZXQtbG9uZ19iYXNlNjRfZm9yX0pXVC1wcm9kdWN0aW9uLXNwcmluZy1ib290Ig=="
      expiration: 86400000 # 24 heures
  main:
    allow-circular-references: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.bar.gestioncocktail: DEBUG
    org.hibernate.SQL: off
