spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_cocktail
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    jwt:
      secret: "${JWT_SECRET}"
      expiration: 86400000 # 24 heures

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.bar.gestioncocktail: DEBUG
    org.hibernate.SQL: off
